package dev.lynx.compose.compiler

import java.io.File

class LynxArtifactEmitter {
  fun emit(page: ComposePage, outputDir: File) {
    outputDir.mkdirs()

    val jsFile = File(outputDir, "${page.entryName}.lynx.js")
    val mainThreadFile = File(outputDir, "${page.entryName}.main-thread.js")
    val ttmlFile = File(outputDir, "${page.entryName}.ttml.json")
    val encodeFile = File(outputDir, "${page.entryName}.encode.json")

    val jsSource = renderJs(page)
    val mainThreadSource = LynxTtmlEmitter.renderMainThreadSource(page)
    val ttmlSource = LynxTtmlEmitter.renderSourceContent(page)
    val encodeSource = LynxTtmlEmitter.renderEncodeJson(page, jsSource, mainThreadSource)

    jsFile.writeText(jsSource)
    mainThreadFile.writeText(mainThreadSource)
    ttmlFile.writeText(ttmlSource)
    encodeFile.writeText(encodeSource)
  }

  private fun renderJs(page: ComposePage): String {
    return """
      // Generated by the compose-lynx demo compiler plugin.
      (function(global) {
        global.initBundle = function initBundle(args) {
          var tt = args && args.tt;
          return {
            entryName: ${json(page.entryName)},
            sourceName: ${json(page.sourceName)},
            hasTT: !!tt
          };
        };
      })(typeof globalThis !== "undefined" ? globalThis : this);
    """.trimIndent()
  }

  private fun json(value: String): String {
    return "\"" + value
      .replace("\\", "\\\\")
      .replace("\"", "\\\"") + "\""
  }
}
