
// This file is autogenerated.

// Copyright 2025 The Lynx Authors. All rights reserved.
// Licensed under the Apache License Version 2.0 that can be found in the
// LICENSE file in the root directory of this source tree.

#include "core/base/android/android_jni.h"

// AUTO_GENERATED_INCLUDE_HEADERS_START
#include "base/include/fml/platform/android/message_loop_android.h"
#include "core/base/android/logging_android.h"
#if TEST_MACRO_
#include "core/runtime/bindings/jsi/modules/android/lynx_promise_impl.h"
#endif
#include "core/runtime/common/utils.h"
#if TEST_MACRO
#include "tools/build_jni/testing/gen/JavaOnlyArray_register_jni.h"
#endif
#include "tools/build_jni/testing/gen/JavaOnlyMap_register_jni.h"
#if TEST_MACRO
#include "tools/build_jni/testing/gen/LayoutNode_register_jni.h"
#endif
#include "tools/build_jni/testing/gen/LynxBackgroundRuntime_register_jni.h"
#include "tools/build_jni/testing/gen/LynxError_register_jni.h"
#include "tools/build_jni/testing/gen/LynxTemplateRender_register_jni.h"

// AUTO_GENERATED_INCLUDE_HEADERS_END

namespace lynx {
namespace jni {
extern "C" JNIEXPORT jint JNI_OnLoad(JavaVM* vm, void* reserved) {
  lynx::base::android::InitVM(vm);
  JNIEnv* env = lynx::base::android::AttachCurrentThread();
  lynx::fml::MessageLoopAndroid::Register(env);
  lynx::base::logging::RegisterJNI(env);
  lynx::piper::JSBUtilsRegisterJNI(env);
  lynx::piper::JSBUtilsMapRegisterJNI(env);
#if TEST_MACRO_
  lynx::piper::LynxPromiseImpl::RegisterJNI(env);
#endif
#if TEST_MACRO
  lynx::jni::RegisterJNIForJavaOnlyArray(env);
#endif
#if TEST_MACRO
  lynx::jni::RegisterJNIForJavaOnlyArray(env);
#endif
  lynx::jni::RegisterJNIForJavaOnlyMapTest(env);
  lynx::jni::RegisterJNIForLynxBackgroundRuntime(env);
  lynx::jni::RegisterJNIForLynxError(env);
  lynx::jni::RegisterJNIForLynxTemplateRender(env);

  return JNI_VERSION_1_6;
}

}  // namespace jni
}  // namespace lynx
