/* C++ code produced by gperf version 3.1 */
/* Computed positions: -k'1,3,13,$' */

#if !(                                                                         \
    (' ' == 32) && ('!' == 33) && ('"' == 34) && ('#' == 35) && ('%' == 37) && \
    ('&' == 38) && ('\'' == 39) && ('(' == 40) && (')' == 41) &&               \
    ('*' == 42) && ('+' == 43) && (',' == 44) && ('-' == 45) && ('.' == 46) && \
    ('/' == 47) && ('0' == 48) && ('1' == 49) && ('2' == 50) && ('3' == 51) && \
    ('4' == 52) && ('5' == 53) && ('6' == 54) && ('7' == 55) && ('8' == 56) && \
    ('9' == 57) && (':' == 58) && (';' == 59) && ('<' == 60) && ('=' == 61) && \
    ('>' == 62) && ('?' == 63) && ('A' == 65) && ('B' == 66) && ('C' == 67) && \
    ('D' == 68) && ('E' == 69) && ('F' == 70) && ('G' == 71) && ('H' == 72) && \
    ('I' == 73) && ('J' == 74) && ('K' == 75) && ('L' == 76) && ('M' == 77) && \
    ('N' == 78) && ('O' == 79) && ('P' == 80) && ('Q' == 81) && ('R' == 82) && \
    ('S' == 83) && ('T' == 84) && ('U' == 85) && ('V' == 86) && ('W' == 87) && \
    ('X' == 88) && ('Y' == 89) && ('Z' == 90) && ('[' == 91) &&                \
    ('\\' == 92) && (']' == 93) && ('^' == 94) && ('_' == 95) &&               \
    ('a' == 97) && ('b' == 98) && ('c' == 99) && ('d' == 100) &&               \
    ('e' == 101) && ('f' == 102) && ('g' == 103) && ('h' == 104) &&            \
    ('i' == 105) && ('j' == 106) && ('k' == 107) && ('l' == 108) &&            \
    ('m' == 109) && ('n' == 110) && ('o' == 111) && ('p' == 112) &&            \
    ('q' == 113) && ('r' == 114) && ('s' == 115) && ('t' == 116) &&            \
    ('u' == 117) && ('v' == 118) && ('w' == 119) && ('x' == 120) &&            \
    ('y' == 121) && ('z' == 122) && ('{' == 123) && ('|' == 124) &&            \
    ('}' == 125) && ('~' == 126))
/* The character set is not based on ISO-646.  */
#error \
    "gperf generated tables don't work with this execution character set. Please report a bug to <bug-gperf@gnu.org>."
#endif

// Copyright 2024 The Lynx Authors. All rights reserved.
// Licensed under the Apache License Version 2.0 that can be found in the
// LICENSE file in the root directory of this source tree.

//
// DO NOT MODIFY THIS FILE! AUTO GENERATED BY clay/tools/make_keywords.py
//

#include "clay/ui/component/keywords.h"

#include <string>

namespace clay {
struct TokenValue {
  short name;
  short id;
};

#define TOTAL_KEYWORDS 261
#define MIN_WORD_LENGTH 3
#define MAX_WORD_LENGTH 37
#define MIN_HASH_VALUE 24
#define MAX_HASH_VALUE 711
/* maximum key range = 688, duplicates = 0 */

class KeywordHash {
 private:
  static inline unsigned int hash(const char *str, size_t len);

 public:
  static const struct TokenValue *find(const char *str, size_t len);
};

inline unsigned int KeywordHash::hash(const char *str, size_t len) {
  static const unsigned short asso_values[] = {
      712, 712, 712, 712, 712, 712, 712, 712, 712, 712, 712, 712, 712, 712, 712,
      712, 712, 712, 712, 712, 712, 712, 712, 712, 712, 712, 712, 712, 712, 712,
      712, 712, 712, 712, 712, 712, 712, 712, 712, 712, 712, 712, 712, 712, 712,
      110, 712, 712, 712, 712, 712, 712, 712, 712, 712, 712, 712, 712, 712, 712,
      712, 712, 712, 712, 712, 712, 712, 712, 712, 712, 712, 712, 712, 712, 712,
      712, 712, 712, 712, 712, 712, 712, 712, 1,   712, 712, 712, 712, 712, 712,
      712, 712, 712, 712, 712, 712, 712, 87,  51,  76,  129, 1,   251, 198, 214,
      114, 4,   1,   115, 13,  84,  214, 26,  712, 11,  6,   3,   238, 43,  158,
      221, 234, 1,   712, 712, 712, 712, 712, 712, 712, 712, 712, 712, 712, 712,
      712, 712, 712, 712, 712, 712, 712, 712, 712, 712, 712, 712, 712, 712, 712,
      712, 712, 712, 712, 712, 712, 712, 712, 712, 712, 712, 712, 712, 712, 712,
      712, 712, 712, 712, 712, 712, 712, 712, 712, 712, 712, 712, 712, 712, 712,
      712, 712, 712, 712, 712, 712, 712, 712, 712, 712, 712, 712, 712, 712, 712,
      712, 712, 712, 712, 712, 712, 712, 712, 712, 712, 712, 712, 712, 712, 712,
      712, 712, 712, 712, 712, 712, 712, 712, 712, 712, 712, 712, 712, 712, 712,
      712, 712, 712, 712, 712, 712, 712, 712, 712, 712, 712, 712, 712, 712, 712,
      712, 712, 712, 712, 712, 712, 712, 712, 712, 712, 712, 712, 712, 712, 712,
      712};
  unsigned int hval = len;

  switch (hval) {
    default:
      hval += asso_values[static_cast<unsigned char>(str[12])];
    /*FALLTHROUGH*/
    case 12:
    case 11:
    case 10:
    case 9:
    case 8:
    case 7:
    case 6:
    case 5:
    case 4:
    case 3:
      hval += asso_values[static_cast<unsigned char>(str[2])];
    /*FALLTHROUGH*/
    case 2:
    case 1:
      hval += asso_values[static_cast<unsigned char>(str[0])];
      break;
  }
  return hval + asso_values[static_cast<unsigned char>(str[len - 1])];
}

struct StringPool_t {
  char StringPool_str24[sizeof("mask")];
  char StringPool_str29[sizeof("mask-size")];
  char StringPool_str30[sizeof("mask-image")];
  char StringPool_str31[sizeof("scroll-left")];
  char StringPool_str32[sizeof("scroll-enable")];
  char StringPool_str33[sizeof("mask-repeat")];
  char StringPool_str34[sizeof("type")];
  char StringPool_str37[sizeof("mask-composite")];
  char StringPool_str43[sizeof("markdown-effect")];
  char StringPool_str46[sizeof("repeat")];
  char StringPool_str48[sizeof("scroll-forward-mode")];
  char StringPool_str49[sizeof("perspective")];
  char StringPool_str53[sizeof("scroll-top")];
  char StringPool_str54[sizeof("mask-clip")];
  char StringPool_str57[sizeof("visible")];
  char StringPool_str58[sizeof("exposure-screen-margin-left")];
  char StringPool_str59[sizeof("exposure-screen-margin-right")];
  char StringPool_str61[sizeof("scroll-bar-track-color")];
  char StringPool_str66[sizeof("exposure-ui-margin-left")];
  char StringPool_str67[sizeof("exposure-ui-margin-right")];
  char StringPool_str69[sizeof("bottom-inset")];
  char StringPool_str70[sizeof("exposure-screen-margin-bottom")];
  char StringPool_str75[sizeof("border-style")];
  char StringPool_str76[sizeof("border-left")];
  char StringPool_str77[sizeof("border-right")];
  char StringPool_str78[sizeof("exposure-ui-margin-bottom")];
  char StringPool_str79[sizeof("border")];
  char StringPool_str80[sizeof("exposure-screen-margin-top")];
  char StringPool_str82[sizeof("border-top-style")];
  char StringPool_str85[sizeof("border-color")];
  char StringPool_str86[sizeof("border-left-style")];
  char StringPool_str87[sizeof("border-radius")];
  char StringPool_str88[sizeof("exposure-ui-margin-top")];
  char StringPool_str91[sizeof("border-top-left-radius")];
  char StringPool_str94[sizeof("prev-scrollable")];
  char StringPool_str95[sizeof("border-bottom-style")];
  char StringPool_str96[sizeof("richtype")];
  char StringPool_str98[sizeof("border-top")];
  char StringPool_str100[sizeof("auto-size")];
  char StringPool_str101[sizeof("border-bottom")];
  char StringPool_str102[sizeof("name")];
  char StringPool_str103[sizeof("adjust-mode")];
  char StringPool_str104[sizeof("cursor")];
  char StringPool_str105[sizeof("border-bottom-color")];
  char StringPool_str106[sizeof("border-bottom-left-radius")];
  char StringPool_str107[sizeof("border-bottom-right-radius")];
  char StringPool_str108[sizeof("tint-color")];
  char StringPool_str109[sizeof("caret-color")];
  char StringPool_str110[sizeof("min-height")];
  char StringPool_str111[sizeof("needs-visible-cells")];
  char StringPool_str112[sizeof("transform")];
  char StringPool_str114[sizeof("mask-origin")];
  char StringPool_str118[sizeof("cap-insets")];
  char StringPool_str119[sizeof("scroll-bar-enable")];
  char StringPool_str120[sizeof("scroll-direction")];
  char StringPool_str122[sizeof("scroll-orientation")];
  char StringPool_str125[sizeof("scroll-backward-mode")];
  char StringPool_str126[sizeof("exposure-scene")];
  char StringPool_str129[sizeof("itemkeys")];
  char StringPool_str130[sizeof("select")];
  char StringPool_str131[sizeof("list-type")];
  char StringPool_str135[sizeof("placeholder")];
  char StringPool_str136[sizeof("idSelector")];
  char StringPool_str139[sizeof("sticky-offset")];
  char StringPool_str140[sizeof("edit-on-focus")];
  char StringPool_str141[sizeof("speed")];
  char StringPool_str142[sizeof("dataset")];
  char StringPool_str147[sizeof("mode")];
  char StringPool_str148[sizeof("background-repeat")];
  char StringPool_str149[sizeof("scroll-event-throttle")];
  char StringPool_str150[sizeof("item-snap")];
  char StringPool_str151[sizeof("typewriter-height-transition-duration")];
  char StringPool_str154[sizeof("markdown-style")];
  char StringPool_str157[sizeof("background-image")];
  char StringPool_str158[sizeof("scroll-to-id")];
  char StringPool_str159[sizeof("vertical-orientation")];
  char StringPool_str161[sizeof("src")];
  char StringPool_str163[sizeof("preload")];
  char StringPool_str164[sizeof("value")];
  char StringPool_str166[sizeof("border-left-color")];
  char StringPool_str167[sizeof("exposure-id")];
  char StringPool_str170[sizeof("content")];
  char StringPool_str173[sizeof("confirm-type")];
  char StringPool_str174[sizeof("controls")];
  char StringPool_str175[sizeof("content-range")];
  char StringPool_str180[sizeof("word-break")];
  char StringPool_str182[sizeof("experimental-recycle-sticky-item")];
  char StringPool_str183[sizeof("consume-slide-event")];
  char StringPool_str184[sizeof("transition")];
  char StringPool_str191[sizeof("border-right-style")];
  char StringPool_str193[sizeof("custom-text-selection")];
  char StringPool_str195[sizeof("cap-insets-scale")];
  char StringPool_str197[sizeof("send-composing-input")];
  char StringPool_str200[sizeof("mask-position")];
  char StringPool_str201[sizeof("border-right-color")];
  char StringPool_str202[sizeof("enable-new-animator")];
  char StringPool_str205[sizeof("border-top-right-radius")];
  char StringPool_str206[sizeof("column-count")];
  char StringPool_str207[sizeof("color")];
  char StringPool_str212[sizeof("enable-insert-platform-view-operation")];
  char StringPool_str213[sizeof("line-height")];
  char StringPool_str214[sizeof("exposure-area")];
  char StringPool_str215[sizeof("allow-escape")];
  char StringPool_str216[sizeof("ignore-focus")];
  char StringPool_str217[sizeof("placeholder-color")];
  char StringPool_str218[sizeof("align-focus")];
  char StringPool_str220[sizeof("smart-scroll")];
  char StringPool_str223[sizeof("skip-redirection")];
  char StringPool_str225[sizeof("outline")];
  char StringPool_str227[sizeof("image-transition-style")];
  char StringPool_str230[sizeof("enable-scrollbar")];
  char StringPool_str231[sizeof("text")];
  char StringPool_str232[sizeof("outline-style")];
  char StringPool_str233[sizeof("direction")];
  char StringPool_str237[sizeof("text-maxline")];
  char StringPool_str238[sizeof("text-indent")];
  char StringPool_str239[sizeof("background-origin")];
  char StringPool_str242[sizeof("animation-type")];
  char StringPool_str243[sizeof("text-gradient")];
  char StringPool_str245[sizeof("auto-save-last-child")];
  char StringPool_str246[sizeof("scroll-x")];
  char StringPool_str247[sizeof("max-height")];
  char StringPool_str248[sizeof("maxlines")];
  char StringPool_str251[sizeof("hit-slop")];
  char StringPool_str252[sizeof("outline-color")];
  char StringPool_str253[sizeof("preferred-focus-child")];
  char StringPool_str254[sizeof("text-mark-attachments")];
  char StringPool_str255[sizeof("intersection-observers")];
  char StringPool_str257[sizeof("background-size")];
  char StringPool_str259[sizeof("scroll-y")];
  char StringPool_str260[sizeof("scroll-bar-thumb-radius")];
  char StringPool_str264[sizeof("scroll-bar-thumb-color")];
  char StringPool_str266[sizeof("background")];
  char StringPool_str270[sizeof("scroll-bar-thumb-hover-color")];
  char StringPool_str271[sizeof("scroll-bar-thumb-active-color")];
  char StringPool_str272[sizeof("disabled")];
  char StringPool_str275[sizeof("show-soft-input-onfocus")];
  char StringPool_str276[sizeof("scroll-bar-auto-hide")];
  char StringPool_str278[sizeof("level")];
  char StringPool_str279[sizeof("list-main-axis-gap")];
  char StringPool_str281[sizeof("scroll-without-focus")];
  char StringPool_str283[sizeof("background-clip")];
  char StringPool_str284[sizeof("white-space")];
  char StringPool_str286[sizeof("prevent-loading-on-list-scroll")];
  char StringPool_str288[sizeof("border-width")];
  char StringPool_str291[sizeof("typewriter-dynamic-height")];
  char StringPool_str292[sizeof("content-complete")];
  char StringPool_str293[sizeof("visibility")];
  char StringPool_str294[sizeof("animation")];
  char StringPool_str296[sizeof("bounce")];
  char StringPool_str299[sizeof("content-id")];
  char StringPool_str302[sizeof("bounces")];
  char StringPool_str303[sizeof("border-top-color")];
  char StringPool_str304[sizeof("transform-origin")];
  char StringPool_str306[sizeof("blur-radius")];
  char StringPool_str308[sizeof("border-bottom-width")];
  char StringPool_str309[sizeof("animation-frame-rate")];
  char StringPool_str311[sizeof("enable-font-scaling")];
  char StringPool_str318[sizeof("text-align")];
  char StringPool_str319[sizeof("auto-fix")];
  char StringPool_str323[sizeof("enable-report-info")];
  char StringPool_str324[sizeof("next-focus-left")];
  char StringPool_str328[sizeof("text-stroke-color")];
  char StringPool_str331[sizeof("enable-scroll")];
  char StringPool_str332[sizeof("autoplay")];
  char StringPool_str337[sizeof("focusable")];
  char StringPool_str338[sizeof("focus")];
  char StringPool_str340[sizeof("readonly")];
  char StringPool_str342[sizeof("loop-count")];
  char StringPool_str343[sizeof("z-index")];
  char StringPool_str344[sizeof("uiappear")];
  char StringPool_str345[sizeof("font-size")];
  char StringPool_str346[sizeof("font-style")];
  char StringPool_str348[sizeof("-x-auto-font-size")];
  char StringPool_str349[sizeof("font-weight")];
  char StringPool_str350[sizeof("vertical-align")];
  char StringPool_str352[sizeof("enable-nested-scroll")];
  char StringPool_str355[sizeof("list-container-info")];
  char StringPool_str357[sizeof("item-key")];
  char StringPool_str358[sizeof("react-ref")];
  char StringPool_str359[sizeof("loop")];
  char StringPool_str360[sizeof("sticky")];
  char StringPool_str361[sizeof("scroll-bar-width")];
  char StringPool_str363[sizeof("initial-animation-step")];
  char StringPool_str366[sizeof("-x-auto-font-size-preset-sizes")];
  char StringPool_str367[sizeof("initial-scroll-offset")];
  char StringPool_str368[sizeof("background-color")];
  char StringPool_str370[sizeof("next-focus-up")];
  char StringPool_str372[sizeof("next-scrollable")];
  char StringPool_str375[sizeof("enable-exposure-ui-clip")];
  char StringPool_str381[sizeof("overflow")];
  char StringPool_str382[sizeof("scroll-to-index")];
  char StringPool_str383[sizeof("filter")];
  char StringPool_str386[sizeof("placeholder-font-size")];
  char StringPool_str387[sizeof("list-cross-axis-gap")];
  char StringPool_str389[sizeof("uidisappear")];
  char StringPool_str390[sizeof("placeholder-font-weight")];
  char StringPool_str393[sizeof("text-shadow")];
  char StringPool_str395[sizeof("user-interaction-enabled")];
  char StringPool_str396[sizeof("block-native-event")];
  char StringPool_str401[sizeof("-x-app-region")];
  char StringPool_str402[sizeof("tag")];
  char StringPool_str403[sizeof("allow-break-around-punctuation")];
  char StringPool_str404[sizeof("border-right-width")];
  char StringPool_str405[sizeof("experimental-batch-render-strategy")];
  char StringPool_str406[sizeof("border-top-width")];
  char StringPool_str409[sizeof("line-spacing")];
  char StringPool_str411[sizeof("image-config")];
  char StringPool_str412[sizeof("next-focus-fallback")];
  char StringPool_str413[sizeof("clip-path")];
  char StringPool_str414[sizeof("letter-spacing")];
  char StringPool_str421[sizeof("accessibility-element")];
  char StringPool_str423[sizeof("experimental-update-sticky-for-diff")];
  char StringPool_str425[sizeof("accessibility-elements")];
  char StringPool_str431[sizeof("need-visible-item-info")];
  char StringPool_str435[sizeof("enable-exposure-ui-margin")];
  char StringPool_str436[sizeof("use-soft-keyboard")];
  char StringPool_str437[sizeof("text-decoration")];
  char StringPool_str438[sizeof("next-focus-right")];
  char StringPool_str440[sizeof("box-shadow")];
  char StringPool_str443[sizeof("event-through")];
  char StringPool_str444[sizeof("background-position")];
  char StringPool_str446[sizeof("overflow-x")];
  char StringPool_str447[sizeof("scroll-monitor-tag")];
  char StringPool_str451[sizeof("border-left-width")];
  char StringPool_str454[sizeof("text-single-line-vertical-align")];
  char StringPool_str455[sizeof("text-maxlength")];
  char StringPool_str457[sizeof("maxlength")];
  char StringPool_str459[sizeof("overflow-y")];
  char StringPool_str461[sizeof("full-screen")];
  char StringPool_str467[sizeof("scroll-bar-thumb-width")];
  char StringPool_str470[sizeof("update-animation")];
  char StringPool_str472[sizeof("scroll-bar-thumb-min-length")];
  char StringPool_str480[sizeof("offset-rotate")];
  char StringPool_str497[sizeof("downsampling")];
  char StringPool_str507[sizeof("upper-threshold-item-count")];
  char StringPool_str512[sizeof("drop-shadow")];
  char StringPool_str515[sizeof("scroll-bar-auto-hide-delay")];
  char StringPool_str516[sizeof("lower-threshold-item-count")];
  char StringPool_str518[sizeof("low-quality")];
  char StringPool_str528[sizeof("image-rendering")];
  char StringPool_str529[sizeof("defer-src-invalidation")];
  char StringPool_str531[sizeof("accessibility-label")];
  char StringPool_str536[sizeof("text-selection")];
  char StringPool_str542[sizeof("opacity")];
  char StringPool_str553[sizeof("text-overflow")];
  char StringPool_str559[sizeof("focus-index")];
  char StringPool_str560[sizeof("custom-context-menu")];
  char StringPool_str565[sizeof("offset-distance")];
  char StringPool_str568[sizeof("animation-velocity")];
  char StringPool_str571[sizeof("focus-smooth-scroll")];
  char StringPool_str580[sizeof("font-family")];
  char StringPool_str584[sizeof("initial-scroll-index")];
  char StringPool_str596[sizeof("fullscreen-mode")];
  char StringPool_str613[sizeof("text-stroke-width")];
  char StringPool_str618[sizeof("next-focus-down")];
  char StringPool_str622[sizeof("upper-threshold")];
  char StringPool_str631[sizeof("lower-threshold")];
  char StringPool_str658[sizeof("outline-width")];
  char StringPool_str690[sizeof("offset-path")];
  char StringPool_str711[sizeof("update-list-info")];
};
static const struct StringPool_t StringPool_contents = {
    "mask",
    "mask-size",
    "mask-image",
    "scroll-left",
    "scroll-enable",
    "mask-repeat",
    "type",
    "mask-composite",
    "markdown-effect",
    "repeat",
    "scroll-forward-mode",
    "perspective",
    "scroll-top",
    "mask-clip",
    "visible",
    "exposure-screen-margin-left",
    "exposure-screen-margin-right",
    "scroll-bar-track-color",
    "exposure-ui-margin-left",
    "exposure-ui-margin-right",
    "bottom-inset",
    "exposure-screen-margin-bottom",
    "border-style",
    "border-left",
    "border-right",
    "exposure-ui-margin-bottom",
    "border",
    "exposure-screen-margin-top",
    "border-top-style",
    "border-color",
    "border-left-style",
    "border-radius",
    "exposure-ui-margin-top",
    "border-top-left-radius",
    "prev-scrollable",
    "border-bottom-style",
    "richtype",
    "border-top",
    "auto-size",
    "border-bottom",
    "name",
    "adjust-mode",
    "cursor",
    "border-bottom-color",
    "border-bottom-left-radius",
    "border-bottom-right-radius",
    "tint-color",
    "caret-color",
    "min-height",
    "needs-visible-cells",
    "transform",
    "mask-origin",
    "cap-insets",
    "scroll-bar-enable",
    "scroll-direction",
    "scroll-orientation",
    "scroll-backward-mode",
    "exposure-scene",
    "itemkeys",
    "select",
    "list-type",
    "placeholder",
    "idSelector",
    "sticky-offset",
    "edit-on-focus",
    "speed",
    "dataset",
    "mode",
    "background-repeat",
    "scroll-event-throttle",
    "item-snap",
    "typewriter-height-transition-duration",
    "markdown-style",
    "background-image",
    "scroll-to-id",
    "vertical-orientation",
    "src",
    "preload",
    "value",
    "border-left-color",
    "exposure-id",
    "content",
    "confirm-type",
    "controls",
    "content-range",
    "word-break",
    "experimental-recycle-sticky-item",
    "consume-slide-event",
    "transition",
    "border-right-style",
    "custom-text-selection",
    "cap-insets-scale",
    "send-composing-input",
    "mask-position",
    "border-right-color",
    "enable-new-animator",
    "border-top-right-radius",
    "column-count",
    "color",
    "enable-insert-platform-view-operation",
    "line-height",
    "exposure-area",
    "allow-escape",
    "ignore-focus",
    "placeholder-color",
    "align-focus",
    "smart-scroll",
    "skip-redirection",
    "outline",
    "image-transition-style",
    "enable-scrollbar",
    "text",
    "outline-style",
    "direction",
    "text-maxline",
    "text-indent",
    "background-origin",
    "animation-type",
    "text-gradient",
    "auto-save-last-child",
    "scroll-x",
    "max-height",
    "maxlines",
    "hit-slop",
    "outline-color",
    "preferred-focus-child",
    "text-mark-attachments",
    "intersection-observers",
    "background-size",
    "scroll-y",
    "scroll-bar-thumb-radius",
    "scroll-bar-thumb-color",
    "background",
    "scroll-bar-thumb-hover-color",
    "scroll-bar-thumb-active-color",
    "disabled",
    "show-soft-input-onfocus",
    "scroll-bar-auto-hide",
    "level",
    "list-main-axis-gap",
    "scroll-without-focus",
    "background-clip",
    "white-space",
    "prevent-loading-on-list-scroll",
    "border-width",
    "typewriter-dynamic-height",
    "content-complete",
    "visibility",
    "animation",
    "bounce",
    "content-id",
    "bounces",
    "border-top-color",
    "transform-origin",
    "blur-radius",
    "border-bottom-width",
    "animation-frame-rate",
    "enable-font-scaling",
    "text-align",
    "auto-fix",
    "enable-report-info",
    "next-focus-left",
    "text-stroke-color",
    "enable-scroll",
    "autoplay",
    "focusable",
    "focus",
    "readonly",
    "loop-count",
    "z-index",
    "uiappear",
    "font-size",
    "font-style",
    "-x-auto-font-size",
    "font-weight",
    "vertical-align",
    "enable-nested-scroll",
    "list-container-info",
    "item-key",
    "react-ref",
    "loop",
    "sticky",
    "scroll-bar-width",
    "initial-animation-step",
    "-x-auto-font-size-preset-sizes",
    "initial-scroll-offset",
    "background-color",
    "next-focus-up",
    "next-scrollable",
    "enable-exposure-ui-clip",
    "overflow",
    "scroll-to-index",
    "filter",
    "placeholder-font-size",
    "list-cross-axis-gap",
    "uidisappear",
    "placeholder-font-weight",
    "text-shadow",
    "user-interaction-enabled",
    "block-native-event",
    "-x-app-region",
    "tag",
    "allow-break-around-punctuation",
    "border-right-width",
    "experimental-batch-render-strategy",
    "border-top-width",
    "line-spacing",
    "image-config",
    "next-focus-fallback",
    "clip-path",
    "letter-spacing",
    "accessibility-element",
    "experimental-update-sticky-for-diff",
    "accessibility-elements",
    "need-visible-item-info",
    "enable-exposure-ui-margin",
    "use-soft-keyboard",
    "text-decoration",
    "next-focus-right",
    "box-shadow",
    "event-through",
    "background-position",
    "overflow-x",
    "scroll-monitor-tag",
    "border-left-width",
    "text-single-line-vertical-align",
    "text-maxlength",
    "maxlength",
    "overflow-y",
    "full-screen",
    "scroll-bar-thumb-width",
    "update-animation",
    "scroll-bar-thumb-min-length",
    "offset-rotate",
    "downsampling",
    "upper-threshold-item-count",
    "drop-shadow",
    "scroll-bar-auto-hide-delay",
    "lower-threshold-item-count",
    "low-quality",
    "image-rendering",
    "defer-src-invalidation",
    "accessibility-label",
    "text-selection",
    "opacity",
    "text-overflow",
    "focus-index",
    "custom-context-menu",
    "offset-distance",
    "animation-velocity",
    "focus-smooth-scroll",
    "font-family",
    "initial-scroll-index",
    "fullscreen-mode",
    "text-stroke-width",
    "next-focus-down",
    "upper-threshold",
    "lower-threshold",
    "outline-width",
    "offset-path",
    "update-list-info"};
#define StringPool ((const char *)&StringPool_contents)

static const struct TokenValue wordlist[] = {
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str24,
     (short)KeywordID::kMask},
    {-1},
    {-1},
    {-1},
    {-1},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str29,
     (short)KeywordID::kMaskSize},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str30,
     (short)KeywordID::kMaskImage},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str31,
     (short)KeywordID::kScrollLeft},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str32,
     (short)KeywordID::kScrollEnable},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str33,
     (short)KeywordID::kMaskRepeat},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str34,
     (short)KeywordID::kType},
    {-1},
    {-1},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str37,
     (short)KeywordID::kMaskComposite},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str43,
     (short)KeywordID::kMarkdownEffect},
    {-1},
    {-1},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str46,
     (short)KeywordID::kRepeat},
    {-1},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str48,
     (short)KeywordID::kScrollForwardMode},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str49,
     (short)KeywordID::kPerspective},
    {-1},
    {-1},
    {-1},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str53,
     (short)KeywordID::kScrollTop},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str54,
     (short)KeywordID::kMaskClip},
    {-1},
    {-1},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str57,
     (short)KeywordID::kVisible},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str58,
     (short)KeywordID::kExposureScreenMarginLeft},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str59,
     (short)KeywordID::kExposureScreenMarginRight},
    {-1},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str61,
     (short)KeywordID::kScrollBarTrackColor},
    {-1},
    {-1},
    {-1},
    {-1},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str66,
     (short)KeywordID::kExposureUiMarginLeft},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str67,
     (short)KeywordID::kExposureUiMarginRight},
    {-1},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str69,
     (short)KeywordID::kBottomInset},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str70,
     (short)KeywordID::kExposureScreenMarginBottom},
    {-1},
    {-1},
    {-1},
    {-1},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str75,
     (short)KeywordID::kBorderStyle},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str76,
     (short)KeywordID::kBorderLeft},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str77,
     (short)KeywordID::kBorderRight},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str78,
     (short)KeywordID::kExposureUiMarginBottom},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str79,
     (short)KeywordID::kBorder},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str80,
     (short)KeywordID::kExposureScreenMarginTop},
    {-1},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str82,
     (short)KeywordID::kBorderTopStyle},
    {-1},
    {-1},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str85,
     (short)KeywordID::kBorderColor},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str86,
     (short)KeywordID::kBorderLeftStyle},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str87,
     (short)KeywordID::kBorderRadius},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str88,
     (short)KeywordID::kExposureUiMarginTop},
    {-1},
    {-1},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str91,
     (short)KeywordID::kBorderTopLeftRadius},
    {-1},
    {-1},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str94,
     (short)KeywordID::kPrevScrollable},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str95,
     (short)KeywordID::kBorderBottomStyle},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str96,
     (short)KeywordID::kRichtype},
    {-1},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str98,
     (short)KeywordID::kBorderTop},
    {-1},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str100,
     (short)KeywordID::kAutoSize},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str101,
     (short)KeywordID::kBorderBottom},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str102,
     (short)KeywordID::kName},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str103,
     (short)KeywordID::kAdjustMode},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str104,
     (short)KeywordID::kCursor},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str105,
     (short)KeywordID::kBorderBottomColor},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str106,
     (short)KeywordID::kBorderBottomLeftRadius},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str107,
     (short)KeywordID::kBorderBottomRightRadius},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str108,
     (short)KeywordID::kTintColor},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str109,
     (short)KeywordID::kCaretColor},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str110,
     (short)KeywordID::kMinHeight},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str111,
     (short)KeywordID::kNeedsVisibleCells},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str112,
     (short)KeywordID::kTransform},
    {-1},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str114,
     (short)KeywordID::kMaskOrigin},
    {-1},
    {-1},
    {-1},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str118,
     (short)KeywordID::kCapInsets},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str119,
     (short)KeywordID::kScrollBarEnable},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str120,
     (short)KeywordID::kScrollDirection},
    {-1},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str122,
     (short)KeywordID::kScrollOrientation},
    {-1},
    {-1},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str125,
     (short)KeywordID::kScrollBackwardMode},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str126,
     (short)KeywordID::kExposureScene},
    {-1},
    {-1},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str129,
     (short)KeywordID::kItemkeys},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str130,
     (short)KeywordID::kSelect},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str131,
     (short)KeywordID::kListType},
    {-1},
    {-1},
    {-1},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str135,
     (short)KeywordID::kPlaceholder},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str136,
     (short)KeywordID::kIdselector},
    {-1},
    {-1},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str139,
     (short)KeywordID::kStickyOffset},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str140,
     (short)KeywordID::kEditOnFocus},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str141,
     (short)KeywordID::kSpeed},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str142,
     (short)KeywordID::kDataset},
    {-1},
    {-1},
    {-1},
    {-1},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str147,
     (short)KeywordID::kMode},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str148,
     (short)KeywordID::kBackgroundRepeat},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str149,
     (short)KeywordID::kScrollEventThrottle},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str150,
     (short)KeywordID::kItemSnap},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str151,
     (short)KeywordID::kTypewriterHeightTransitionDuration},
    {-1},
    {-1},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str154,
     (short)KeywordID::kMarkdownStyle},
    {-1},
    {-1},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str157,
     (short)KeywordID::kBackgroundImage},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str158,
     (short)KeywordID::kScrollToId},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str159,
     (short)KeywordID::kVerticalOrientation},
    {-1},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str161,
     (short)KeywordID::kSrc},
    {-1},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str163,
     (short)KeywordID::kPreload},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str164,
     (short)KeywordID::kValue},
    {-1},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str166,
     (short)KeywordID::kBorderLeftColor},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str167,
     (short)KeywordID::kExposureId},
    {-1},
    {-1},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str170,
     (short)KeywordID::kContent},
    {-1},
    {-1},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str173,
     (short)KeywordID::kConfirmType},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str174,
     (short)KeywordID::kControls},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str175,
     (short)KeywordID::kContentRange},
    {-1},
    {-1},
    {-1},
    {-1},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str180,
     (short)KeywordID::kWordBreak},
    {-1},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str182,
     (short)KeywordID::kExperimentalRecycleStickyItem},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str183,
     (short)KeywordID::kConsumeSlideEvent},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str184,
     (short)KeywordID::kTransition},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str191,
     (short)KeywordID::kBorderRightStyle},
    {-1},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str193,
     (short)KeywordID::kCustomTextSelection},
    {-1},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str195,
     (short)KeywordID::kCapInsetsScale},
    {-1},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str197,
     (short)KeywordID::kSendComposingInput},
    {-1},
    {-1},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str200,
     (short)KeywordID::kMaskPosition},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str201,
     (short)KeywordID::kBorderRightColor},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str202,
     (short)KeywordID::kEnableNewAnimator},
    {-1},
    {-1},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str205,
     (short)KeywordID::kBorderTopRightRadius},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str206,
     (short)KeywordID::kColumnCount},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str207,
     (short)KeywordID::kColor},
    {-1},
    {-1},
    {-1},
    {-1},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str212,
     (short)KeywordID::kEnableInsertPlatformViewOperation},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str213,
     (short)KeywordID::kLineHeight},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str214,
     (short)KeywordID::kExposureArea},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str215,
     (short)KeywordID::kAllowEscape},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str216,
     (short)KeywordID::kIgnoreFocus},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str217,
     (short)KeywordID::kPlaceholderColor},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str218,
     (short)KeywordID::kAlignFocus},
    {-1},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str220,
     (short)KeywordID::kSmartScroll},
    {-1},
    {-1},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str223,
     (short)KeywordID::kSkipRedirection},
    {-1},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str225,
     (short)KeywordID::kOutline},
    {-1},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str227,
     (short)KeywordID::kImageTransitionStyle},
    {-1},
    {-1},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str230,
     (short)KeywordID::kEnableScrollbar},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str231,
     (short)KeywordID::kText},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str232,
     (short)KeywordID::kOutlineStyle},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str233,
     (short)KeywordID::kDirection},
    {-1},
    {-1},
    {-1},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str237,
     (short)KeywordID::kTextMaxline},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str238,
     (short)KeywordID::kTextIndent},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str239,
     (short)KeywordID::kBackgroundOrigin},
    {-1},
    {-1},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str242,
     (short)KeywordID::kAnimationType},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str243,
     (short)KeywordID::kTextGradient},
    {-1},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str245,
     (short)KeywordID::kAutoSaveLastChild},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str246,
     (short)KeywordID::kScrollX},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str247,
     (short)KeywordID::kMaxHeight},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str248,
     (short)KeywordID::kMaxlines},
    {-1},
    {-1},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str251,
     (short)KeywordID::kHitSlop},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str252,
     (short)KeywordID::kOutlineColor},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str253,
     (short)KeywordID::kPreferredFocusChild},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str254,
     (short)KeywordID::kTextMarkAttachments},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str255,
     (short)KeywordID::kIntersectionObservers},
    {-1},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str257,
     (short)KeywordID::kBackgroundSize},
    {-1},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str259,
     (short)KeywordID::kScrollY},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str260,
     (short)KeywordID::kScrollBarThumbRadius},
    {-1},
    {-1},
    {-1},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str264,
     (short)KeywordID::kScrollBarThumbColor},
    {-1},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str266,
     (short)KeywordID::kBackground},
    {-1},
    {-1},
    {-1},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str270,
     (short)KeywordID::kScrollBarThumbHoverColor},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str271,
     (short)KeywordID::kScrollBarThumbActiveColor},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str272,
     (short)KeywordID::kDisabled},
    {-1},
    {-1},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str275,
     (short)KeywordID::kShowSoftInputOnfocus},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str276,
     (short)KeywordID::kScrollBarAutoHide},
    {-1},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str278,
     (short)KeywordID::kLevel},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str279,
     (short)KeywordID::kListMainAxisGap},
    {-1},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str281,
     (short)KeywordID::kScrollWithoutFocus},
    {-1},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str283,
     (short)KeywordID::kBackgroundClip},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str284,
     (short)KeywordID::kWhiteSpace},
    {-1},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str286,
     (short)KeywordID::kPreventLoadingOnListScroll},
    {-1},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str288,
     (short)KeywordID::kBorderWidth},
    {-1},
    {-1},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str291,
     (short)KeywordID::kTypewriterDynamicHeight},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str292,
     (short)KeywordID::kContentComplete},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str293,
     (short)KeywordID::kVisibility},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str294,
     (short)KeywordID::kAnimation},
    {-1},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str296,
     (short)KeywordID::kBounce},
    {-1},
    {-1},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str299,
     (short)KeywordID::kContentId},
    {-1},
    {-1},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str302,
     (short)KeywordID::kBounces},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str303,
     (short)KeywordID::kBorderTopColor},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str304,
     (short)KeywordID::kTransformOrigin},
    {-1},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str306,
     (short)KeywordID::kBlurRadius},
    {-1},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str308,
     (short)KeywordID::kBorderBottomWidth},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str309,
     (short)KeywordID::kAnimationFrameRate},
    {-1},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str311,
     (short)KeywordID::kEnableFontScaling},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str318,
     (short)KeywordID::kTextAlign},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str319,
     (short)KeywordID::kAutoFix},
    {-1},
    {-1},
    {-1},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str323,
     (short)KeywordID::kEnableReportInfo},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str324,
     (short)KeywordID::kNextFocusLeft},
    {-1},
    {-1},
    {-1},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str328,
     (short)KeywordID::kTextStrokeColor},
    {-1},
    {-1},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str331,
     (short)KeywordID::kEnableScroll},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str332,
     (short)KeywordID::kAutoplay},
    {-1},
    {-1},
    {-1},
    {-1},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str337,
     (short)KeywordID::kFocusable},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str338,
     (short)KeywordID::kFocus},
    {-1},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str340,
     (short)KeywordID::kReadonly},
    {-1},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str342,
     (short)KeywordID::kLoopCount},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str343,
     (short)KeywordID::kZIndex},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str344,
     (short)KeywordID::kUiappear},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str345,
     (short)KeywordID::kFontSize},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str346,
     (short)KeywordID::kFontStyle},
    {-1},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str348,
     (short)KeywordID::kXAutoFontSize},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str349,
     (short)KeywordID::kFontWeight},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str350,
     (short)KeywordID::kVerticalAlign},
    {-1},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str352,
     (short)KeywordID::kEnableNestedScroll},
    {-1},
    {-1},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str355,
     (short)KeywordID::kListContainerInfo},
    {-1},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str357,
     (short)KeywordID::kItemKey},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str358,
     (short)KeywordID::kReactRef},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str359,
     (short)KeywordID::kLoop},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str360,
     (short)KeywordID::kSticky},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str361,
     (short)KeywordID::kScrollBarWidth},
    {-1},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str363,
     (short)KeywordID::kInitialAnimationStep},
    {-1},
    {-1},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str366,
     (short)KeywordID::kXAutoFontSizePresetSizes},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str367,
     (short)KeywordID::kInitialScrollOffset},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str368,
     (short)KeywordID::kBackgroundColor},
    {-1},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str370,
     (short)KeywordID::kNextFocusUp},
    {-1},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str372,
     (short)KeywordID::kNextScrollable},
    {-1},
    {-1},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str375,
     (short)KeywordID::kEnableExposureUiClip},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str381,
     (short)KeywordID::kOverflow},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str382,
     (short)KeywordID::kScrollToIndex},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str383,
     (short)KeywordID::kFilter},
    {-1},
    {-1},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str386,
     (short)KeywordID::kPlaceholderFontSize},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str387,
     (short)KeywordID::kListCrossAxisGap},
    {-1},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str389,
     (short)KeywordID::kUidisappear},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str390,
     (short)KeywordID::kPlaceholderFontWeight},
    {-1},
    {-1},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str393,
     (short)KeywordID::kTextShadow},
    {-1},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str395,
     (short)KeywordID::kUserInteractionEnabled},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str396,
     (short)KeywordID::kBlockNativeEvent},
    {-1},
    {-1},
    {-1},
    {-1},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str401,
     (short)KeywordID::kXAppRegion},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str402,
     (short)KeywordID::kTag},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str403,
     (short)KeywordID::kAllowBreakAroundPunctuation},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str404,
     (short)KeywordID::kBorderRightWidth},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str405,
     (short)KeywordID::kExperimentalBatchRenderStrategy},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str406,
     (short)KeywordID::kBorderTopWidth},
    {-1},
    {-1},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str409,
     (short)KeywordID::kLineSpacing},
    {-1},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str411,
     (short)KeywordID::kImageConfig},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str412,
     (short)KeywordID::kNextFocusFallback},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str413,
     (short)KeywordID::kClipPath},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str414,
     (short)KeywordID::kLetterSpacing},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str421,
     (short)KeywordID::kAccessibilityElement},
    {-1},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str423,
     (short)KeywordID::kExperimentalUpdateStickyForDiff},
    {-1},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str425,
     (short)KeywordID::kAccessibilityElements},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str431,
     (short)KeywordID::kNeedVisibleItemInfo},
    {-1},
    {-1},
    {-1},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str435,
     (short)KeywordID::kEnableExposureUiMargin},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str436,
     (short)KeywordID::kUseSoftKeyboard},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str437,
     (short)KeywordID::kTextDecoration},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str438,
     (short)KeywordID::kNextFocusRight},
    {-1},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str440,
     (short)KeywordID::kBoxShadow},
    {-1},
    {-1},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str443,
     (short)KeywordID::kEventThrough},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str444,
     (short)KeywordID::kBackgroundPosition},
    {-1},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str446,
     (short)KeywordID::kOverflowX},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str447,
     (short)KeywordID::kScrollMonitorTag},
    {-1},
    {-1},
    {-1},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str451,
     (short)KeywordID::kBorderLeftWidth},
    {-1},
    {-1},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str454,
     (short)KeywordID::kTextSingleLineVerticalAlign},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str455,
     (short)KeywordID::kTextMaxlength},
    {-1},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str457,
     (short)KeywordID::kMaxlength},
    {-1},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str459,
     (short)KeywordID::kOverflowY},
    {-1},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str461,
     (short)KeywordID::kFullScreen},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str467,
     (short)KeywordID::kScrollBarThumbWidth},
    {-1},
    {-1},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str470,
     (short)KeywordID::kUpdateAnimation},
    {-1},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str472,
     (short)KeywordID::kScrollBarThumbMinLength},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str480,
     (short)KeywordID::kOffsetRotate},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str497,
     (short)KeywordID::kDownsampling},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str507,
     (short)KeywordID::kUpperThresholdItemCount},
    {-1},
    {-1},
    {-1},
    {-1},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str512,
     (short)KeywordID::kDropShadow},
    {-1},
    {-1},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str515,
     (short)KeywordID::kScrollBarAutoHideDelay},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str516,
     (short)KeywordID::kLowerThresholdItemCount},
    {-1},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str518,
     (short)KeywordID::kLowQuality},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str528,
     (short)KeywordID::kImageRendering},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str529,
     (short)KeywordID::kDeferSrcInvalidation},
    {-1},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str531,
     (short)KeywordID::kAccessibilityLabel},
    {-1},
    {-1},
    {-1},
    {-1},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str536,
     (short)KeywordID::kTextSelection},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str542,
     (short)KeywordID::kOpacity},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str553,
     (short)KeywordID::kTextOverflow},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str559,
     (short)KeywordID::kFocusIndex},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str560,
     (short)KeywordID::kCustomContextMenu},
    {-1},
    {-1},
    {-1},
    {-1},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str565,
     (short)KeywordID::kOffsetDistance},
    {-1},
    {-1},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str568,
     (short)KeywordID::kAnimationVelocity},
    {-1},
    {-1},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str571,
     (short)KeywordID::kFocusSmoothScroll},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str580,
     (short)KeywordID::kFontFamily},
    {-1},
    {-1},
    {-1},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str584,
     (short)KeywordID::kInitialScrollIndex},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str596,
     (short)KeywordID::kFullscreenMode},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str613,
     (short)KeywordID::kTextStrokeWidth},
    {-1},
    {-1},
    {-1},
    {-1},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str618,
     (short)KeywordID::kNextFocusDown},
    {-1},
    {-1},
    {-1},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str622,
     (short)KeywordID::kUpperThreshold},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str631,
     (short)KeywordID::kLowerThreshold},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str658,
     (short)KeywordID::kOutlineWidth},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str690,
     (short)KeywordID::kOffsetPath},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {-1},
    {(short)(size_t) & ((struct StringPool_t *)0)->StringPool_str711,
     (short)KeywordID::kUpdateListInfo}};

const struct TokenValue *KeywordHash::find(const char *str, size_t len) {
  if (len <= MAX_WORD_LENGTH && len >= MIN_WORD_LENGTH) {
    unsigned int key = hash(str, len);

    if (key <= MAX_HASH_VALUE) {
      int o = wordlist[key].name;
      if (o >= 0) {
        const char *s = o + StringPool;

        if (*str == *s && !strcmp(str + 1, s + 1)) return &wordlist[key];
      }
    }
  }
  return 0;
}

static_assert(sizeof(StringPool_contents) < 32767);

KeywordID GetKeywordID(const std::string &str) {
  auto *tk = KeywordHash::find(str.c_str(), str.size());
  return tk ? static_cast<KeywordID>(tk->id) : KeywordID::kInvalid;
}

}  // namespace clay
