name: build harmony explorer

description: build harmony explorer hap

runs:
  using: composite
  steps:
    - name: Install Common Dependencies
      uses: ./lynx/.github/actions/common-deps
      with:
        cache-key-prefix: '-container'
    - name: Build Explorer App
      shell: bash
      working-directory: lynx
      run: |-
        source tools/envsetup.sh
        pushd platform/harmony && ohpm install && popd
        pushd explorer/harmony && ohpm install && popd
        python3 explorer/harmony/script/build.py --dev --build_lynx_core --build_bundle --build_hap
    - name: upload artifact
      uses: lynx-infra/upload-artifact@332ec52e99f7cbf1fbbdc9bcc09280d49147d092
      continue-on-error: true
      with:
        name: harmony-lynx-explorer
        path: '${{ github.workspace }}/lynx/explorer/harmony/lynx_explorer/build/default/outputs/default/lynx_explorer-default-unsigned.hap'
