// Copyright 2024 The Lynx Authors. All rights reserved.
// Licensed under the Apache License Version 2.0 that can be found in the
// LICENSE file in the root directory of this source tree.

export class LynxUIMethodConstants {
  public static SUCCESS = 0;
  public static UNKNOWN = 1;
  public static NODE_NOT_FOUND = 2;
  public static METHOD_NOT_FOUND = 3;
  public static PARAM_INVALID = 4;
  public static SELECTOR_NOT_SUPPORTED = 5;
  public static NO_UI_FOR_NODE = 6;
  public static INVALID_STATE_ERROR = 7;
  public static OPERATION_ERROR = 8;
}
