# Copyright 2025 The Lynx Authors. All rights reserved.
# Licensed under the Apache License Version 2.0 that can be found in the
# LICENSE file in the root directory of this source tree.

extraInfo:
  description: user defined extraInfo.
  defaultValue: null
  valueType: lepus::Value
  syncTo:
    - script
  codeGen:
    - MEMBER
    - SETTER
    - GETTER
  nameAs:
    const: kUserDefinedExtraInfo
customCSSInheritanceList:
  description:
  defaultValue: null
  valueType: std::unordered_set<CSSPropertyID>
  bindMemberTo: css_configs_.custom_inherit_list_
  codeGen:
    - SETTER
    - GETTER
  nameAs:
    setter: SetCustomCSSInheritList
    getter: GetCustomCSSInheritList
version:
  description:
  defaultValue: null
  valueType: string
  nameAs:
    member: page_version
cli:
  description: cli version
  defaultValue: null
  valueType: string
  nameAs:
    member: cli_version
    setter: SetCliVersion
    getter: GetCliVersion
    const: kCliVersion
reactVersion:
  description:
  defaultValue: null
  valueType: string
customData:
  description:
  defaultValue: null
  valueType: string
tapSlop:
  description:
  defaultValue: 50px
  valueType: string
preferredFps:
  description:
  defaultValue: 'auto'
  valueType: string
quirksMode:
  description:
  defaultValue: 'base::Version(1, 5)'
  valueType: base::Version
  codeGen:
    - NONE
enableLynxScrollFluency:
  description: Force report lynx scroll fluency event. When setting pageConfig.enableLynxScrollFluency to a double value in the range [0, 1], we will monitor the fluency metrics for this LynxUI based on this probability. The probability indicates the likelihood of enabling fluency monitoring, and the metrics will be reported unconditionally through the applogService.
  defaultValue: -1
  valueType: double
  syncTo:
    - script
  codeGen:
    - MEMBER
  nameAs:
    member: enable_scroll_fluency_monitor
lepusGCThreshold:
  description: GC threshold of lepusNG. Let default value be 256, and the unit is KB.
  defaultValue: 256
  valueType: int64_t
pipelineSchedulerConfig:
  description: Scheduler config for pipeline, including enableParallelElement/list-framework batch render and other scheduler config.
  defaultValue: 0
  valueType: uint64_t
  readNative: true
  author: 'usczz'
redBoxImageSizeWarningThreshold:
  description: null
  defaultValue: 1000000
  valueType: uint32_t
  nameAs:
    member: log_box_image_size_warning_threshold
    setter: SetLogBoxImageSizeWarningThreshold
    getter: GetLogBoxImageSizeWarningThreshold
    const: kLogBoxImageSizeWarningThreshold
lepusQuickjsStacksize:
  description: null
  defaultValue: 0
  valueType: uint32_t
  nameAs:
    member: lepus_quickjs_stack_size
    setter: SetLepusQuickjsStackSize
    getter: GetLepusQuickjsStackSize
observerFrameRate:
  description:
  defaultValue: 20
  valueType: int32_t
longPressDuration:
  description:
  defaultValue: -1
  valueType: int32_t
useNewImage:
  description: null
  defaultValue: TernaryBool::UNDEFINE_VALUE
  valueType: TernaryBool
enableTextBoringLayout:
  description: Enable Android text BoringLayout.
  defaultValue: TernaryBool::UNDEFINE_VALUE
  valueType: TernaryBool
enableTextLayerRender:
  description:
  defaultValue: TernaryBool::UNDEFINE_VALUE
  valueType: TernaryBool
enableUseMapBuffer:
  description:
  defaultValue: TernaryBool::UNDEFINE_VALUE
  valueType: TernaryBool
  readNative: true
  author: 'nhsprite'
enableFiberElementForRadonDiff:
  description:
  defaultValue: TernaryBool::UNDEFINE_VALUE
  valueType: TernaryBool
  author: 'DragonDragonDDD'
  readNative: true
enableOptPushStyleToBundle:
  description:
  defaultValue: TernaryBool::UNDEFINE_VALUE
  valueType: TernaryBool
  author: 'ShouruiSong'
  readNative: true
enableTextLayoutCache:
  description:
  defaultValue: TernaryBool::UNDEFINE_VALUE
  valueType: TernaryBool
enableUnifiedPipeline:
  description:
  defaultValue: TernaryBool::UNDEFINE_VALUE
  valueType: TernaryBool
  author: 'nhsprite'
  readNative: true
enableUseContextPool:
  description:
  defaultValue: TernaryBool::UNDEFINE_VALUE
  valueType: TernaryBool
  codeGen:
    - MEMBER
    - SETTER
    - DECODE
enableCSSLazyImport:
  description:
  defaultValue: TernaryBool::UNDEFINE_VALUE
  valueType: TernaryBool
  codeGen:
    - MEMBER
    - SETTER
    - DECODE
enableNewAnimator:
  description:
  defaultValue: TernaryBool::UNDEFINE_VALUE
  valueType: TernaryBool
  codeGen:
    - MEMBER
    - SETTER
    - DECODE
enableComponentAsyncDecode:
  description: Enable dynamic components to be decoded in child threads before they are delivered into tasm in async-loading.
  defaultValue: TernaryBool::UNDEFINE_VALUE
  valueType: TernaryBool
  codeGen:
    - MEMBER
    - SETTER
    - DECODE
enableSignalAPI:
  description:
  defaultValue: TernaryBool::UNDEFINE_VALUE
  valueType: TernaryBool
  readNative: true
  author: 'ShouruiSong'
enableNativeScheduleCreateViewAsync:
  description:
  defaultValue: TernaryBool::UNDEFINE_VALUE
  valueType: TernaryBool
  readNative: true
  author: 'ShouruiSong'
enableNativeList:
  description: Indicates whether use c++ list.
  defaultValue: TernaryBool::UNDEFINE_VALUE
  valueType: TernaryBool
  readNative: true
  author: 'DwwWxx'
trailNewImage:
  description:
  defaultValue: TernaryBool::UNDEFINE_VALUE
  valueType: TernaryBool
  readNative: true
  author: 'liubb0516'
asyncRedirect:
  description:
  defaultValue: TernaryBool::UNDEFINE_VALUE
  valueType: TernaryBool
  nameAs:
    member: async_redirect_url
    setter: SetAsyncRedirectUrl
    getter: GetAsyncRedirectUrl
  readNative: true
  author: 'liubb0516'
enableUIOperationOptimize:
  description: Enable the optimization aboult UIOperation batching and CreateViewAsync at Android.
  defaultValue: TernaryBool::UNDEFINE_VALUE
  valueType: TernaryBool
  readNative: true
enableMicrotaskPromisePolyfill:
  description:
  defaultValue: TernaryBool::UNDEFINE_VALUE
  valueType: TernaryBool
  readNative: true
mapContainerType:
  description:
  defaultValue: 0
  valueType: uint8_t
flatten:
  description:
  defaultValue: true
  valueType: bool
  nameAs:
    member: page_flatten
    setter: SetGlobalFlattern
    getter: GetGlobalFlattern
implicit:
  description: null
  defaultValue: true
  valueType: bool
  versionOverrides:
    - minSDKVersion: LYNX_VERSION_2_0
      value: 'false'
  nameAs:
    member: page_implicit
    setter: SetGlobalImplicit
    getter: GetGlobalImplicit
lepusStrict:
  description: null
  defaultValue: false
  valueType: bool
  nameAs:
    member: enable_lepus_strict_check
    setter: SetEnableLepusStrictCheck
    getter: GetEnableLepusStrictCheck
lepusNullPropAsUndef:
  description: null
  defaultValue: false
  valueType: bool
  versionOverrides:
    - minSDKVersion: LYNX_VERSION_1_6
      value: 'true'
  nameAs:
    member: enable_lepus_null_prop_as_undef
    setter: SetEnableLepusNullPropAsUndef
    getter: GetEnableLepusNullPropAsUndef
dataStrictMode:
  description: null
  defaultValue: true
  valueType: bool
enableAsyncDisplay:
  description: null
  defaultValue: true
  valueType: bool
enableImageDownsampling:
  description: null
  defaultValue: false
  valueType: bool
enableNewImage:
  description: null
  defaultValue: true
  valueType: bool
enableTextNonContiguousLayout:
  description: null
  defaultValue: true
  valueType: bool
enableViewReceiveTouch:
  description: null
  defaultValue: false
  valueType: bool
enableEventThrough:
  description: null
  defaultValue: false
  valueType: bool
removeComponentElement:
  description: null
  defaultValue: false
  valueType: bool
  nameAs:
    member: need_remove_component_element
strictPropType:
  description: null
  defaultValue: false
  valueType: bool
syncImageAttach:
  description: null
  defaultValue: true
  valueType: bool
useImagePostProcessor:
  description: null
  defaultValue: false
  valueType: bool
useNewSwiper:
  description: null
  defaultValue: true
  valueType: bool
enableAsyncInitVideoEngine:
  description: null
  defaultValue: false
  valueType: bool
  nameAs:
    member: async_init_tt_video_engine
    setter: SetEnableAsyncInitTTVideoEngine
    getter: GetEnableAsyncInitTTVideoEngine
enableComponentLifecycleAlignWebview:
  description:
  defaultValue: false
  valueType: bool
enableListNewArchitecture:
  description:
  defaultValue: false
  valueType: bool
  nameAs:
    member: list_new_architecture
    setter: SetListNewArchitecture
    getter: GetListNewArchitecture
enableNewListContainer:
  description:
  defaultValue: false
  valueType: bool
enableListPlug:
  description:
  defaultValue: false
  valueType: bool
  nameAs:
    member: list_enable_plug
enableListMoveOperation:
  description:
  defaultValue: false
  valueType: bool
  nameAs:
    member: list_enable_move_operation
enableCreateViewAsync:
  description:
  defaultValue: true
  valueType: bool
enableVsyncAlignedFlush:
  description:
  defaultValue: false
  valueType: bool
enableAccessibilityElement:
  description:
  defaultValue: true
  valueType: bool
enableOverlapForAccessibilityElement:
  description:
  defaultValue: true
  valueType: bool
enableNewAccessibility:
  description:
  defaultValue: false
  valueType: bool
enableNewLayoutOnly:
  description:
  defaultValue: true
  valueType: bool
enableReactOnlyPropsId:
  description:
  defaultValue: false
  valueType: bool
enableGlobalComponentMap:
  description:
  defaultValue: false
  valueType: bool
enableTextRefactor:
  description:
  defaultValue: false
  valueType: bool
  versionOverrides:
    - minSDKVersion: LYNX_VERSION_2_2
      value: 'true'
enableTextOverflow:
  description: Set text overflow as visible if true.
  defaultValue: false
  valueType: bool
  versionOverrides:
    - minSDKVersion: LYNX_VERSION_2_8
      value: 'true'
enableNewClipMode:
  description: Set new clip mode if true.
  defaultValue: true
  valueType: bool
  versionOverrides:
    - minSDKVersion: LYNX_VERSION_2_10
      value: 'true'
autoResumeAnimation:
  description:
  defaultValue: true
  valueType: bool
  versionOverrides:
    - minSDKVersion: LYNX_VERSION_2_3
      value: 'true'
  nameAs:
    setter: SetGlobalAutoResumeAnimation
    getter: GetGlobalAutoResumeAnimation
enableNewTransformOrigin:
  description: If this flag is true, new transform origin algorithm will apply.
  defaultValue: true
  valueType: bool
  versionOverrides:
    - minSDKVersion: LYNX_VERSION_2_6
      value: 'true'
  nameAs:
    setter: SetGlobalEnableNewTransformOrigin
    getter: GetGlobalEnableNewTransformOrigin
enableCircularDataCheck:
  description: If this flag is true, circular data check will enable when convert js value to other vale.
  defaultValue: true
  valueType: bool
  nameAs:
    setter: SetGlobalCircularDataCheck
    getter: GetGlobalCircularDataCheck
enableReduceInitDataCopy:
  description:
  defaultValue: false
  valueType: bool
enableSimultaneousTap:
  description:
  defaultValue: false
  valueType: bool
enableComponentLayoutOnly:
  description:
  defaultValue: false
  valueType: bool
  versionOverrides:
    - minSDKVersion: LYNX_VERSION_2_6
      value: 'true'
extendedLayoutOnlyOpt:
  description: A config to force make some special properties can be used to layout only (such as direction&text-align,etc.).
  defaultValue: false
  valueType: bool
  versionOverrides:
    - minSDKVersion: LYNX_VERSION_2_13
      value: 'true'
  nameAs:
    setter: SetEnableExtendedLayoutOpt
    getter: GetEnableExtendedLayoutOpt
enableTouchRefactor:
  description: Default value is false. If this flag is true, the external gesture which's state is possible or began will not cancel the Lynx iOS touch gesture see issue:#7920.
  defaultValue: true
  valueType: bool
enableEndGestureAtLastFingerUp:
  description: In the previous commit, when determining whether all fingers had moved off the screen in multiple touch scenarios, touch.view was used for judgment. However, in a scrolling container, touch.view obtained from touchesEnd/touchesMove could be nil, resulting in incorrect judgment of whether all fingers had moved off the screen. _touches could not be cleared, leading to a subsequent failure to trigger tap events. To fix this issue, we added null checks before calling touch.view, and ended the gesture if _touches was empty. This resolved the problem. Only for ios, detail can see f-12375631 and its mr.
  defaultValue: false
  valueType: bool
disableLongpressAfterScroll:
  description: If this flag is true, iOS will not recognize the corresponding long press gesture after triggering scrolling.
  defaultValue: false
  valueType: bool
keyboardCallbackPassRelativeHeight:
  description:
  defaultValue: false
  valueType: bool
  versionOverrides:
    - minSDKVersion: LYNX_VERSION_2_2
      value: 'true'
  nameAs:
    setter: SetKeyboardCallbackUseRelativeHeight
    getter: GetKeyboardCallbackUseRelativeHeight
enableCheckDataWhenUpdatePage:
  description:
  defaultValue: true
  valueType: bool
enableBackgroundShapeLayer:
  description: Enable iOS background manager to apply shape layer optimization.
  defaultValue: true
  valueType: bool
compileRender:
  description:
  defaultValue: false
  valueType: bool
enableTextLanguageAlignment:
  description:
  defaultValue: false
  valueType: bool
enableXTextLayoutReused:
  description:
  defaultValue: false
  valueType: bool
enableRemoveComponentExtraData:
  description:
  defaultValue: false
  valueType: bool
enableExposureUIMargin:
  description:
  defaultValue: false
  valueType: bool
enableNewGesture:
  description: Enable gesture handler.
  defaultValue: false
  valueType: bool
enablePlatformGesture:
  description: Enable shadow platform gesture to handle gesture conflict.
  defaultValue: false
  valueType: bool
  since: 3.6
enableCheckLocalImage:
  description:
  defaultValue: true
  valueType: bool
enableAsyncRequestImage:
  description:
  defaultValue: false
  valueType: bool
enableComponentNullProp:
  description: Support component can be passed null props, null props only supported in LepusNG now. Open this switch to support lepus use null prop.
  defaultValue: false
  valueType: bool
enableCascadePseudo:
  description:
  defaultValue: false
  valueType: bool
autoExpose:
  description:
  defaultValue: true
  valueType: bool
  nameAs:
    member: enable_auto_show_hide
disableQuickTracingGC:
  description: Disable tracing gc mode in quick context.
  defaultValue: false
  valueType: bool
fixCSSImportRuleOrder:
  description:
  defaultValue: true
  valueType: bool
enableReloadLifecycle:
  description: Enable LynxUI onNodeReload lifecycle.
  defaultValue: false
  valueType: bool
  author: 'nhsprite'
enableA11y:
  description: Enable Android A11y
  defaultValue: false
  valueType: bool
  author: 'DwwWxx'
enableA11yIDMutationObserver:
  description: Enable MutationObserver for accessibility.
  defaultValue: false
  valueType: bool
  author: 'MoonfaceX'
  nameAs:
    member: enable_a11y_mutation_observer
enableCheckExposureOptimize:
  description: Enable exposure detection optimization.
  defaultValue: false
  valueType: bool
  author: 'rAY-ooo'
enableDisexposureWhenLynxHidden:
  description: Enable send disexposure events when lynxview is hidden.
  defaultValue: true
  valueType: bool
  author: 'rAY-ooo'
enableExposureWhenLayout:
  description: Enable exposure check when LynxView is layoutRequest
  defaultValue: false
  valueType: bool
  author: 'ShouruiSong'
enableAirDetectRemovedKeysWhenUpdateData:
  description: enable Air Mode detect removed keys when updating data from native
  defaultValue: false
  valueType: bool
enableJSDataProcessor:
  description: Enable data processor on JS thread
  defaultValue: false
  valueType: bool
  author: 'ShouruiSong'
  nameAs:
    member: enable_data_processor_on_js
    setter: SetEnableDataProcessorOnJs
    getter: GetEnableDataProcessorOnJs
enableJsBindingApiThrowException:
  description: Enable js binding api throw exception
  defaultValue: false
  valueType: bool
  versionOverrides:
    - minSDKVersion: LYNX_VERSION_2_14
      value: 'true'
  author: 'lybvinci'
enableICU:
  description: Enable Bind PRIMJS-ICU
  defaultValue: false
  valueType: bool
  syncTo:
    - script
  author: 'OverWatch-Winder'
  nameAs:
    member: enable_bind_icu
    setter: SetEnableBindICU
    getter: GetEnableBindICU
    const: kEnableBindICU
enableQueryComponentSync:
  description: Enable query component sync in background runtime
  defaultValue: false
  valueType: bool
  author: 'Awuiil'
enableAsyncResolveSubtree:
  description: FE Framework use this config to notify Engine that resolve subtree binding will be triggered when render DOM (Not exposed to normal user)
  defaultValue: TernaryBool::UNDEFINE_VALUE
  valueType: TernaryBool
  author: 'usczz'
  nameAs:
    const: kEnableAsyncFlushSubtree
absoluteInContentBound:
  description:
  defaultValue: false
  valueType: bool
  bindMemberTo: layout_configs_.is_absolute_in_content_bound_
  codeGen:
    - SETTER
    - GETTER
    - DECODE
enableFixedNew:
  description:
  defaultValue: false
  valueType: bool
  bindMemberTo: layout_configs_.enable_fixed_new_
  codeGen:
    - SETTER
    - GETTER
    - DECODE
  readSettings: true
enableCSSInheritance:
  description:
  defaultValue: false
  valueType: bool
  bindMemberTo: css_configs_.enable_css_inheritance_
  codeGen:
    - SETTER
    - GETTER
    - DECODE
CSSAlignWithLegacyW3C:
  description:
  defaultValue: false
  valueType: bool
  codeGen:
    - MEMBER
    - DECODE
enableCSSStrictMode:
  description:
  defaultValue: false
  valueType: bool
  bindMemberTo: css_parser_configs_.enable_css_strict_mode
  codeGen:
    - SETTER
    - GETTER
    - DECODE
unifyVWVHBehavior:
  description:
  defaultValue: false
  valueType: bool
  versionOverrides:
    - minSDKVersion: LYNX_VERSION_2_3
      value: 'true'
  codeGen:
    - SETTER
    - GETTER
    - DECODE
  nameAs:
    setter: SetUnifyVWVH
    getter: GetUnifyVWVH
  bindMemberTo: css_configs_.unify_vw_vh_behavior_
fontScaleEffectiveOnlyOnSp:
  description:
  defaultValue: false
  valueType: bool
  bindMemberTo: layout_configs_.font_scale_sp_only_
  codeGen:
    - SETTER
    - GETTER
    - DECODE
  nameAs:
    setter: SetFontScaleSpOnly
    getter: GetFontScaleSpOnly
enableNewIntersectionObserver:
  description:
  defaultValue: false
  valueType: bool
  readSettings: true
forceCalcNewStyle:
  description:
  defaultValue: true
  valueType: bool
  codeGen:
    - SETTER
    - GETTER
    - MEMBER
  nameAs:
    const: kForceCalcNewStyleKey
includeFontPadding:
  description:
  defaultValue: false
  valueType: bool
  codeGen:
    - DECODE
removeDescendantSelectorScope:
  description: If false, descendant selector only works in component scope.
  defaultValue: true
  valueType: bool
  syncTo:
    - script
  codeGen:
    - MEMBER
    - SETTER
    - GETTER
enableMultiTouch:
  description: Enable support multi-finger events
  defaultValue: false
  valueType: bool
  author: 'rAY-ooo'
  readSettings: true
enableMultiTouchParamsCompatible:
  description: Enable support multi-finger event parameter compatibility
  defaultValue: false
  valueType: bool
  codeGen:
    - MEMBER
    - SETTER
    - GETTER
  author: 'rAY-ooo'
enableHarmonyVisibleAreaChangeForExposure:
  description: Enable Harmony to detect exposure with visible area change event.
  defaultValue: false
  valueType: bool
  author: 'rAY-ooo'
enableTextGradientOpt:
  description: Enable text gradient optimization for iOS.
  defaultValue: TernaryBool::UNDEFINE_VALUE
  valueType: TernaryBool
  readSettings: false
  settingsEnv: external
  syncTo: platform
  author: 'zhongyr'
  readNative: true
