name: install common dependencies

description: pull common source and binary dependencies via habitat.

inputs:
  concurrency:
    description: concurrency of requests
    default: '2'
    required: false
  cache-backend:
    description: cache backend for habitat
    default: 'lynx-infra'
    required: false
  target:
    description: habitat target
    default: ''
    required: false
  # actions/cache stores files with relative directory, which causes inconsistency between self-hosted runner and
  # container runner. Therefore, add this temporary option to modify cache key prefix as a workaround. Delete this when
  # we are able to adjust the container runner's directory structure to the same as self-hosted runner.
  cache-key-prefix:
    description: cache key prefix for cache action
    default: ''
    required: false

runs:
  using: composite
  steps:
    - name: setup cache action
      if: ${{ inputs.cache-backend == 'lynx-infra' }}
      uses: lynx-infra/cache@5c6160a6a4c7fca80a2f3057bb9dfc9513fcb732
      with:
        path: ~/.habitat_cache
        key: hab${{ inputs.cache-key-prefix }}-${{ runner.os }}-${{ hashFiles('lynx/.habitat', 'lynx/DEPS') }}
        restore-keys: |
          hab${{ inputs.cache-key-prefix }}-${{ runner.os }}-

    - name: setup cache action
      if: ${{ inputs.cache-backend == 'github' }}
      uses: actions/cache@v4
      with:
        path: ~/.habitat_cache
        key: hab-${{ runner.os }}-${{ hashFiles('lynx/.habitat', 'lynx/DEPS') }}
        restore-keys: |
          hab-${{ runner.os }}-

    - name: Get Python Cache Directory
      id: pip
      shell: bash
      if: ${{ inputs.cache-backend == 'lynx-infra' }}
      run: echo "PIP_CACHE_DIR=$(python3 -m pip cache dir)" >> $GITHUB_OUTPUT

    - name: Python Requirements Cache
      if: ${{ inputs.cache-backend == 'lynx-infra' }}
      uses: lynx-infra/cache@5c6160a6a4c7fca80a2f3057bb9dfc9513fcb732
      with:
        path: ${{ steps.pip.outputs.PIP_CACHE_DIR }}
        key: pip${{ inputs.cache-key-prefix }}-${{ runner.os }}

    - name: install Python dependencies
      shell: bash
      run: |
        if [ "$RUNNER_OS" == "macOS" ]; then
          python3 -m pip install PyYAML==6.0.2 --break-system-packages
          python3 -m pip install requests==2.32.5 --break-system-packages
        else
          python3 -m pip install PyYAML==6.0.2
          python3 -m pip install requests==2.32.5
        fi

    - name: run habitat sync
      shell: bash
      working-directory: lynx
      run: |
        if [[ "${{ inputs.target }}" == "" ]]; then
          tools/hab sync .
        else
          tools/hab sync . --target ${{ inputs.target }}
        fi
      env:
        HABITAT_CONCURRENCY: ${{ inputs.concurrency }}
